config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :reviews, only: %i[new create destroy]
  end
  root to: "pages#home"
  get :dashboard, to: 'pages#dashboard', as: "dashboard"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :reviews, only: %i[new create destroy]
  resources :offers, only: %i[index show new create edit update destroy] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
  before_save :calculate_duration

  private

  def calculate_duration
    self.duration = (end_date - start_date).to_i
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :name, :category, :description, :address, :price_per_day, presence: true
  validates :category, inclusion: { in: ["Baby-sitting/Garde d'enfants", "Maison/Décoration", "Réparation/Entretien", "Dog-sitting/Garde d'animaux", "Jardin/Extérieur", "Animation", "Traiteur/Service à table" ] }
  validates :name, length: { minimum: 3 }
  validates :description, length: { minimum: 6 }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORY = ["Baby-sitting/Garde d'enfants", "Maison/Décoration", "Réparation/Entretien", "Dog-sitting/Garde d'animaux", "Jardin/Extérieur", "Animation", "Traiteur/Service à table" ]

  before_save :attach_photo

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: %i[name description],
  using: {
    tsearch: { prefix: true }
  }

  include PgSearch::Model
  pg_search_scope :search_by_category,
  against: %i[category],
  using: {
    tsearch: { prefix: true }
  }

  private

  def attach_photo
    if photo.attached?
      return
    else
    category_images = {
      CATEGORY[0] => 'babysitting.jpg',
      CATEGORY[1] => 'maison2.jpeg',
      CATEGORY[2] => 'reparation.jpg',
      CATEGORY[3] => 'dog.jpg',
      CATEGORY[4] => 'jardin.png',
      CATEGORY[5] => 'animation2.jpeg',
      CATEGORY[6] => 'traiteur.jpg'
    }

    image_filename = category_images[self.category] || 'logo2.png'
    image_path = File.join(Rails.root, 'app/assets/images', image_filename)

    self.photo.attach(io: File.open(image_path), filename: 'image')
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews
  has_many :offers
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show destroy]
  skip_before_action :authenticate_user!, only: %i[new create]
  def show
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = @offer
    @booking.total_price = (@booking.end_date - @booking.start_date + 1).to_i * @offer.price_per_day
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :offer_id, :start_date, :end_date, :duration)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[show destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @offers = policy_scope(Offer)
    if params[:jardin_exterieur]
      @offers = @offers.where(category: "Jardin/Extérieur")
    elsif params[:babysitting]
      @offers = @offers.where(category: "Baby-sitting/Garde d'enfants")
    elsif params[:dogsitting]
      @offers = @offers.where(category: "Dog-sitting/Garde d'animaux")
    elsif params[:reparation]
      @offers = @offers.where(category: "Réparation/Entretien")
    elsif params[:house]
      @offers = @offers.where(category: "Maison/Décoration")
    elsif params[:party]
      @offers = @offers.where(category: "Animation")
    elsif params[:cook]
      @offers = @offers.where(category: "Traiteur/Service à table")
    elsif params[:query].present?
      @offers = Offer.search_by_name_and_description(params[:query])
    else
      @offers = Offer.all
    end
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude
      }
    end
  end

  def show
    authorize @offer
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
    authorize @offer
  end

  def new
    @offer = Offer.new
    @offer.user = current_user
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_path
    authorize @offer
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:price_per_day, :name, :description, :category, :address, :beginning_date, :end_date, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def home
    @offers = Offer.all.sample(3)
  end

  def dashboard
    @bookings = current_user.bookings
    @offers = current_user.offers
    @bookings_requests = Booking.all.select { |booking| booking.offer.user == current_user }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end


  def create
    @review = Review.new(review_params)
    @user = Review.find(params[:user_id])
    @review.user = @user
    if @review.save
      redirect_to user_path
    else
      @review = Review.new
      render 'users/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to user_path(@review.user)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="banner" id="booking" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path@offer.photo.key, position: :center %>);">
    <div class="container text-center">
      <h1><strong><%= @offer.name %></strong></h1>
      <h3><strong><%= @offer.category %></strong></h3>
    </div>
</div>

<div class="container">
  <div class="bookings_show d-flex my-5">
    <div class="w-25 p-2">
      <h3><strong>Je vous propose:</strong><h3>
      <h6> <strong>Description:</strong> <%= @offer.description %></h6>
      <h6><strong>Adresse:</strong> <%= @offer.address %></h6>
      <h6><strong>Prix par jour:</strong> <%= @offer.price_per_day %> €</h6>
    </div>

    <div class="justify-content-center mx-3" id="map">
      <div style="width: 600px; height: 400px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>

    <div class="card_flatpickr">
      <div class="cards p-5 unique-card">
        <%= simple_form_for [@offer, @booking], data: { controller: 'flatpickr' } do |f| %>
          <%= f.input :start_date, as: :string, input_html: { id: "start_date", data: { flatpickr_target: "startDate" } } %>
          <%= f.input :end_date, as: :string, input_html: { id: "end_date",  data: { flatpickr_target: "endDate" } } %>
          <%= f.input :duration, as: :hidden %>
          <button type="submit" class="btn btn_schedule">Réservez ce service</button>
        <% end %>
        <h4><%= @booking.total_price %></h4>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForyouApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/d7f03b659a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/offers/edit.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3769999/pexels-photo-3769999.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <div class="container p-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3 class="text-center">Créez votre offre</h3>
          <%= simple_form_for @offer do |f| %>
            <%= f.input :name, placeholder: 'Quel service proposez-vous ?' %>
            <%= f.input :description, placeholder: 'Décrivez en quelques mots votre service' %>
            <%= f.input :category, collection: Offer::CATEGORY %>
            <%= f.input :price_per_day%>
            <%= f.input :address %>
            <%= f.input :photo, as: :file %>
            <%= f.submit 'Modifiez votre offre', class: 'btn-show-offer w-100' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="bg-white">
  <div class="container p-4 bg-white">
  <h1 class="mb-4 text-center">Trouvez l'offre qui vous correspond</h1>
    <%# SEARCH BAR %>
    <%= form_with url: offers_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "i.e: Babysitting"
      %>
      <%= submit_tag "Recherchez", class: "violet-button" %>
    <% end %>
    <%# FIN SEARCH BAR %>
    <%# ICONS RECHERCHE %>

    <div class="icon-bar">
      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "jardin_exterieur" do %>
          <i class="fa-solid fa-seedling"></i>
          <p>Jardin/Extérieur</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "babysitting" do %>
          <i class="fa-solid fa-baby-carriage"></i>
          <p>Baby-sitting/Garde d'enfants</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "dogsitting" do %>
          <i class="fa-solid fa-dog"></i>
          <p>Dog-sitting/Garde d'animaux</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "reparation" do %>
          <i class="fa-solid fa-screwdriver-wrench"></i>
          <p>Réparation/Entretien</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "house" do %>
          <i class="fa-solid fa-house"></i>
          <p>Maison/Décoration</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "party" do %>
          <i class="fa-solid fa-cake-candles"></i>
          <p>Animation</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "cook" do %>
          <i class="fa-solid fa-utensils"></i>
          <p>Traiteur/Service à table</p>
        <% end %>
      <% end %>

      <%= form_tag offers_path, method: :get do %>
        <%= button_tag type: "submit", class: "btn btn-default", name: "all_offers" do %>
        <i class="fa-solid fa-rotate-left"></i>
        <p>Toutes les catégories</p>
        <% end %>
      <% end %>
    </div>
    <%# FIN ICONS RECHERCHE %>
      <div class="align-items-center my-3">
        <div style="width: 100%; height: 300px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    <div class="cards">
      <% @offers.each do |offer| %>
          <div class="card-offer position-relative">
            <%= link_to new_offer_booking_path(offer), id: "card-link" do %>
              <%= cl_image_tag offer.photo.key, width: 450, height: 200, style: "object-fit: cover"%>
              <div class="card-offer-infos">
                <h3><%= truncate(offer.name, length: 40, separator: ' ', omission: '...') %></h3>
                <em><h5><%= offer.category %></h5></em>
                <p><%= truncate(offer.description, length: 40, separator: ' ', omission: '...') %></p>
                </div>
                <div class="card-offer-person">
                    <h4 class="card-offer-pricing"><%= offer.price_per_day %> € /jour</h4>
                </div>
                <div class="position-absolute" style="top: 180px; right: 20px;">
                  <img src="<%= Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
                </div>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3769999/pexels-photo-3769999.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <div class="container p-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <h3 class="text-center">Créez votre offre</h3>
          <%= simple_form_for @offer do |f| %>
            <%= f.input :name, label: 'Nom', placeholder: 'Quel service proposez-vous ?' %>
            <%= f.input :description, label: 'Description', placeholder: 'Décrivez en quelques mots votre service' %>
            <%= f.input :category, label: 'Catégorie', collection: Offer::CATEGORY %>
            <%= f.input :price_per_day, label: 'Prix par jour'%>
            <%= f.input :address, label: 'Adresse' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit "Créez votre offre", class:'btn-show-offer w-100' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="bg-white p-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="text-center">
        <%= cl_image_tag @offer.photo.key, width: 680 %>
      </div>
      <div class="mx-auto">
        <h2 class="text-center pt-5" style="color: #3C1A5B"><strong>Mon offre for you...</strong></h2>
        <P><strong>Nom:</strong> <%= @offer.name %></P>
        <p> <strong>Description:</strong> <%= @offer.description %></p>
        <p> <strong>Catégorie:</strong> <%= @offer.category %></p>
        <p><strong>Adresse:</strong> <%= @offer.address %></p>
        <p><strong>Prix:</strong> <%= @offer.price_per_day %> €</p>
        <div class="d-flex justify-content-between">
          <%= link_to "Mettre à jour l'offre", edit_offer_path(@offer), class: 'btn btn-update me-30'%>
          <%= link_to "Supprimer l'offre", offer_path(@offer),
          data: {turbo_method: :delete, turbo_confirm: "êtes vous sûr?"}, class: 'btn btn-destroy me-30'%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container my-4">
  <h1 class="text-center mb-5 mt-5">Mon tableau de bord</h1>

  <h4 class="my-4">Mes réservations</h4>

    <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card-offer position-relative">
          <%= link_to new_offer_booking_path(booking.offer), id: "card-link" do %>
            <%= cl_image_tag booking.offer.photo.key,
            width: 450, height: 200, style: "object-fit: cover" %>
              <div class="position-absolute" style="top: 180px; right: 20px;">
                  <img src="<%= Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
              </div>
            <div class="card-offer-infos">
              <div>
                <h2><%= truncate(booking.offer.name, length: 35, separator: ' ', omission: '...') %> </h2>
                <em><%= booking.offer.category %></em>
                <p><%= truncate(booking.offer.description, length: 80, separator: ' ', omission: '...') %></p>
                <p><strong>du <%= booking.start_date %> au <%= booking.end_date %></strong></p>
                <br>
              </div>
              <div class="d-flex justify-content-between">
                <h3 class="card-offer-pricing mb-4">Prix total : <%= booking.total_price %>€</h3>
                <%= link_to "Supprimer ce booking", booking_path(booking),
                data: {turbo_method: :delete, turbo_confirm: "êtes vous sûr?"}, class: 'btn btn-secondary position-absolute', style: 'opacity: 0.9; top: 115px; right: 20px;'%>
              </div>
            </div>
            <% end %>
        </div>
      <% end %>

     </div>



  <h4 class="my-3">Mes offres</h4>
  <div class="cards">
    <% @offers.each do |offer| %>
        <div class="card-offer position-relative">
          <%= link_to offer_path(offer), id: "card-link" do %>
            <%= cl_image_tag offer.photo.key, width: 450, height: 200, style: "object-fit: cover"%>
            <div class="card-offer-infos">
              <h3><%= truncate(offer.name, length: 40, separator: ' ', omission: '...') %></h3>
              <em><h5><%= offer.category %></h5></em>
              <p><%= truncate(offer.description, length: 40, separator: ' ', omission: '...') %></p>
              </div>
              <div class="card-offer-person">
                  <h4 class="card-offer-pricing"><%= offer.price_per_day %> € /jour</h4>
              </div>
              <div class="position-absolute" style="top: 180px; right: 20px;">
                <img src="<%= Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
              </div>
          <% end %>
        </div>
    <% end %>
  </div>


  <h4 class="my-3">Réservation en attente</h4>
   <div class="cards">
    <% @bookings_requests.each do |request| %>
      <div class="card-offer position-relative">
        <%= cl_image_tag request.offer.photo.key,
        width: 450, height: 200, style: "object-fit: cover"%>
        <div class="card-offer-infos">
          <div>
            <h2><%= request.offer.name %> </h2>
            <em><%= request.offer.category %></em>
            <p><%= request.offer.description %></p>
            <p><strong><%= request.start_date %> to <%= request.end_date %></strong></p>
          </div>
        </div>
        <div class="position-absolute" style="top: 180px; right: 20px;">
          <img src="<%= Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
        </div>
        <div class="d-flex justify-content-around mt-3 mb-3">
            <h4 class="card-offer-pricing"><%= request.offer.price_per_day %>€/jour</h4>
          <button type="button" class="btn btn-secondary"> Accepter </button>
          <%= link_to "Refuser", booking_path(request), data: {turbo_method: :delete, turbo_confirm: "êtes vous sûr?"},  class: "btn btn-secondary"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/3217156/pexels-photo-3217156.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <div class="container">
    <h1>ForYou</h1>
    <p>Babysitting, bricolage, jardinage, traiteur, dog-sitting... for you !</p>
    <%= link_to 'Réservez maintenant', offers_path, class: 'btn btn-flat' %>
  </div>
</div>

<div class="bg-white">
  <div class="container p-5 bg-white">
    <h1 class="text-center">Ils proposent leur service :</h1>
    <div class="cards p-5">

     <% @offers.each do |offer| %>
          <div class="card-offer position-relative">
            <%= link_to new_offer_booking_path(offer), id: "card-link" do %>
            <%= cl_image_tag offer.photo.key, width: 450, height: 200, style: "object-fit: cover"%>
            <div class="card-offer-infos">
              <h3><%= truncate(offer.name, length: 40, separator: ' ', omission: '...') %></h3>
              <em><h5><%= offer.category %></h5></em>
              <p><%= truncate(offer.description, length: 40, separator: ' ', omission: '...') %></p>
              </div>
              <div class="card-offer-person">
                  <h4 class="card-offer-pricing"><%= offer.price_per_day %> € /jour</h4>
              </div>
              <div class="position-absolute" style="top: 180px; right: 20px;">
                <img src="<%= Faker::Avatar.image%>" class="card-trip-user avatar-bordered" />
              </div>
            <% end %>
          </div>
      <% end %>
    </div>
    <div class="text-center text-decoration-none">
      <%= link_to "Voir toutes les offres", offers_path, class: 'btn btn-show-offer w-50' %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright text-center">
    <h6>This app is made with <i class="fas fa-heart"></i> for you</h6>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "foryou.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Les offres", offers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Proposez vos services", new_offer_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/thibmer49", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon tableau de bord", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Mes infos", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>